import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/footer";
import Header from "./components/navbar";
import { CartProvider } from "./components/cart";
import TopHeader from "./components/topheader";
import { ImageProvider } from "@/context/imagecontext";  // Ensure correct import path

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <ImageProvider> {/* ✅ ImageProvider added here */}
            <TopHeader />
            <Header />
            {children}
            <Footer />
          </ImageProvider>
        </CartProvider>
      </body>
    </html>
  );
}
